# Generated by Django 4.0.6 on 2022-07-26 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webcontactdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_contactno', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
                ('web_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web_address', models.CharField(blank=True, max_length=100, null=True)),
                ('web_worktime', models.CharField(blank=True, max_length=50, null=True)),
                ('web_workdate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
