# Generated by Django 4.0.6 on 2022-07-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcontactdetails',
            name='web_workdate',
        ),
    ]
