# Generated by Django 4.0.5 on 2022-07-08 12:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lead.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_code', models.CharField(max_length=50, unique=True)),
                ('ban_img', models.FileField(default='webbanners/default.jpg', upload_to=lead.models.banner_path)),
                ('ban_comments', models.CharField(max_length=50)),
                ('ban_update_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_code', models.CharField(max_length=50, unique=True)),
                ('con_name', models.CharField(max_length=50)),
                ('con_mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('con_email', models.EmailField(max_length=254)),
                ('con_document', models.FileField(default='connector_documents/default.jpg', upload_to=lead.models.con_doc_path)),
                ('con_account_no', models.DecimalField(decimal_places=0, max_digits=20)),
                ('con_ifsc_code', models.CharField(max_length=50)),
                ('con_bank_name', models.CharField(max_length=50)),
                ('con_branch', models.CharField(max_length=50)),
                ('con_reg_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Service_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='lead.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_code', models.CharField(max_length=50, unique=True)),
                ('lead_date', models.DateField(default=django.utils.timezone.now)),
                ('party_name', models.CharField(blank=True, max_length=50, null=True)),
                ('party_mobile', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('party_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('party_address', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('CLOSE', 'CLOSE'), ('CANCEL', 'CANCEL')], default='PENDING', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.category', verbose_name='category')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.connector', verbose_name='connector')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.service_types', verbose_name='services')),
            ],
        ),
    ]
