# Generated by Django 4.0.6 on 2022-07-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('0', 'PENDING'), ('1', 'APPROVED'), ('2', 'CLOSE'), ('3', 'CANCEL')], default='PENDING', max_length=100),
        ),
    ]
