# Generated by Django 4.0.6 on 2022-07-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('CLOSE', 'CLOSE'), ('CANCEL', 'CANCEL')], default='PENDING', max_length=100),
        ),
    ]
