# Generated by Django 4.0.6 on 2022-07-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='con_revenue',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
