# Generated by Django 4.0.6 on 2022-07-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_connector_con_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='con_revenue',
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.connector', verbose_name='connector')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.lead', verbose_name='lead')),
            ],
        ),
    ]
