# Generated by Django 4.0.5 on 2022-07-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('CLOSE', 'CLOSE'), ('CANCEL', 'CANCEL')], default='PENDING', max_length=100),
        ),
    ]
