# Generated by Django 4.0.6 on 2022-07-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_remove_connector_con_revenue_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='connector',
        ),
    ]
