# Generated by Django 4.0.6 on 2022-07-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_remove_revenue_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('CLOSE', 'CLOSE'), ('CANCEL', 'CANCEL')], default='PENDING', max_length=100),
        ),
    ]
