# Generated by Django 4.0.5 on 2022-07-08 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_alter_category_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lead.category', verbose_name='category'),
            preserve_default=False,
        ),
    ]
