# Generated by Django 4.0.6 on 2022-07-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_revenue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETE', 'COMPLETE'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=100),
        ),
    ]
