# Generated by Django 4.0.6 on 2022-07-26 05:37

from django.db import migrations, models
import django.utils.timezone
import lead.models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_lead_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_code', models.CharField(max_length=50, unique=True)),
                ('ban_img', models.FileField(default='webbanners/default.jpg', upload_to=lead.models.banner_path)),
                ('ban_comments', models.CharField(max_length=50)),
                ('ban_update_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
