# Generated by Django 4.0.6 on 2022-07-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_lead_con_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='con_revenue',
            new_name='con_paid_revenue',
        ),
        migrations.AddField(
            model_name='lead',
            name='con_paybal_revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='lead',
            name='con_revenue_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=100),
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
