# Generated by Django 4.0.6 on 2022-07-26 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='con_paid_revenue',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='con_paybal_revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='lead',
            name='con_revenue_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('CANCEL', 'CANCEL')], default='PENDING', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='trx_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lead',
            name='trx_no',
            field=models.CharField(default=0, max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('CLOSE', 'CLOSE'), ('CANCEL', 'CANCEL')], default='PENDING', max_length=100, null=True),
        ),
    ]
