# Generated by Django 4.0.6 on 2022-07-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0014_lead_trx_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='trx_id',
            new_name='trx_no',
        ),
    ]
