# Generated by Django 4.0.6 on 2022-07-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0016_alter_lead_trx_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='trx_no',
            field=models.CharField(default=0, max_length=254),
        ),
    ]
